FROM node:16-alpine

ARG PUBLIC_URL=/

RUN corepack enable yarn && apk add --no-cache autoconf automake libtool make tiff jpeg zlib zlib-dev pkgconf nasm file gcc g++ musl-dev python3 git

WORKDIR /app
COPY ./.yarn /app/.yarn
COPY package.json yarn.lock .yarnrc.yml /app/
RUN yarn install --immutable

COPY babel.config.js vue.config.js README.md /app/

COPY ./build/loaders /app/build/loaders

# Note: ./bin, ./public, ./translations, and ./src are mounted as volumes
# so they will be hot-reloaded when changed

EXPOSE 10010

CMD ["yarn", "serve", "--host", "0.0.0.0"]

